force-app/main/default/objects/MyCustomObj__c/MyCustomObj__c.object-meta.xml
<CustomObject>
    <label>MyCustomObj</label>
    <nameField>
        <label>MyCustomObj名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MyCustomObj__c/fields/maker__c.field-meta.xml
<CustomField>
    <fullName>maker__c</fullName>
    <label>メーカー</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>トヨタ</fullName>
            </value>
            <value>
                <fullName>ホンダ</fullName>
            </value>
            <value>
                <fullName>日産</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MyCustomObj__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>値段</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/ApexCallManager.cls
public with sharing class ApexCallManager {
    @AuraEnabled
    public static List<MyCustomObj__c> serachCarRecord( String keyWord , Integer minPrice){
        if ( keyWord == null ) {
            return [
                SELECT
                    Id,
                    Name,
                    maker__c,
                    Price__c
                FROM MyCustomObj__c
                WHERE Price__c >= :minPrice
            ];
        }
        keyWord = keyWord.trim();
        keyWord = '%' + keyWord + '%';
        return [
                SELECT
                    Id,
                    Name,
                    maker__c,
                    Price__c
                FROM MyCustomObj__c
                WHERE Price__c >= :minPrice AND
                    Name LIKE :keyWord
            ];
    }
}